### ISSUE TITLE
refactor object update w/ null support

### ISSUE THREAD

**Issue by claire-lemon** [lemoncloud-io/lemon-core#154]
# 개요
### object update w/ null support

# 상황 설명
### 문제 대상 
elastic6-service 내 updateItem()

### 문제 상황

updateItem에서 object를 업데이트 할 때, 다음과 같은 상황이 발생한다.

1. 업데이트 하고자하는 객체의 키 값이 이미 존재한다면 >> 정상적으로 update 된다.
ex) ` { a: 1 } -> { a:null } >> final = { a:null }`

2. 새로운 키 값을 가진 객체로 update한다면 >> 각각의 객체가 merge된다.
ex) `{ a:1 } -> { b:null } >> final = { a:1, b:null }`

### TODO
- [ ] object를 어떤 값으로 update하더라도 merge되지 않고 해당 값으로만 update되도록 수정

**Comment by steve-lemon** [comment]
improved since `3.2.9`
