### ISSUE TITLE
body가 함수여서 루프에러 날 수 있는건가요?

### ISSUE THREAD

**Issue by tyler9410** [lemoncloud-io/lemon-core#80]
https://github.com/lemoncloud-io/lemon-core/blob/c2628566c19cd84cc5aa9cd33a71dd9f4a37d59b/src/cores/api-service.ts#L602

**Comment by steve-lemon** [comment]
do you mean `typeof body == 'function'` ?

**Comment by tyler9410** [comment]
Yes right, I'll check this code via `npm link` then tell you later

**Comment by tyler9410** [comment]
CLEAR!!
